language: generic

addons:
  apt:
    packages:
      - python3
      - python3-lxml
      - python3-requests

script:
- make find
- make file | tee log
- make find-unfiled
# Next line checks if anything needs to be created
- test $(make find-unfiled | wc -l) -eq 0 
