language: generic

addons:
  apt:
    packages:
      - python3
      - python3-lxml
      - python3-requests

script:
- make find
- make file | tee log
# Next line checks if anything needs to be created
- grep -v "hub issue create" log
